### PR TITLE
Thprd branch

### PR DESCRIPTION
**Pull request by drpht**
hi, wintel I have create a new index file with new style sheet, please review it.

### CODE REVIEW

**Comment by wintel2006** [comment]
you forget to turn on the stylesheet file.

**Comment by drpht** [comment]
sorry, rush, now check again

**Comment by wintel2006** [comment]
I do not like one big style sheet file, can you do it seperately

**Comment by wintel2006** [comment]
good, I will merge the new changes for newindex and newstyle.css, and I will add the 4th block of stylesheet later

**Pull request merged**
